# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import exception as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.log_exception(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "u\nfr=8tt)@M$t\x0cYTWY"
    dict_0 = {str_0: str_0}
    module_0.log_exception(dict_0, dict_0, **dict_0)


def test_case_2():
    str_0 = "\x0c>:U^$m?\x0b>)hZS"
    var_0 = module_0.log_exception(str_0, str_0)


def test_case_3():
    var_0 = module_0.exception_wrapper()


def test_case_4():
    none_type_0 = module_0.register_ipython_excepthook()
